CREATE TABLE USER_DETAILS (
	id VARCHAR(255) PRIMARY KEY,
	email VARCHAR(255) NOT NULL
);

CREATE TABLE USER_DATABASES (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	database_name VARCHAR(255) NOT NULL,
	user_id VARCHAR NOT NULL,
	CONSTRAINT fk_user
		FOREIGN KEY(user_id)
		REFERENCES USER_DETAILS (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE USER_TABLES (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	tablename VARCHAR(255) NOT NULL,
	user_database_id UUID NOT NULL,
	CONSTRAINT fk_user_database
		FOREIGN KEY(user_database_id)
		REFERENCES USER_DATABASES (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE TABLE_VARIABLES (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	variable_name VARCHAR(255),
	variable_type VARCHAR(255),
	pk_flag BOOLEAN NULL,
	fk_flag BOOLEAN NULL,
	fk_ref_id UUID NULL,
	usertable_id UUID NOT NULL,
	CONSTRAINT fk_usertable
		FOREIGN KEY(usertable_id)
		REFERENCES USER_TABLES (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT fk_table_variable
		FOREIGN KEY(fk_ref_id)
		REFERENCES TABLE_VARIABLES (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);







